name: Build and Push Docker Image

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - dev
      - demo
  workflow_dispatch: # Add this line to enable manual triggering

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        if: ${{ github.ref_name == 'main' }}
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Log in to Azure Container Registry (Dev/Demo)
        if: ${{ github.ref_name == 'dev' || github.ref_name == 'demo' }}
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_DEV_LOGIN_SERVER }}
          username: ${{ secrets.ACR_DEV_USERNAME }}
          password: ${{ secrets.ACR_DEV_PASSWORD }}

      - name: Set Docker image tag
        id: docker_tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "TAG=dev" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/demo" ]]; then
            echo "TAG=demo" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        if: ${{ github.ref_name == 'main' }}
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/webapp:${{ env.TAG }} -f WebApp.Dockerfile .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/webapp:${{ env.TAG }}

      - name: Build and push Docker image (Dev/Demo)
        if: ${{ github.ref_name == 'dev' || github.ref_name == 'demo' }}
        run: |
          docker build -t ${{ secrets.ACR_DEV_LOGIN_SERVER }}/webapp:${{ env.TAG }} -f WebApp.Dockerfile .
          docker push ${{ secrets.ACR_DEV_LOGIN_SERVER }}/webapp:${{ env.TAG }}